import { Injectable, BadRequestException, ForbiddenException, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, In } from 'typeorm';
import axios from 'axios';
import { PlanEntity, PlanStatus, PlanType } from '../plans/entities/plan.entity';
import { UserEntity, UserRole } from '../users/entities/user.entity';
import { NotificationsService } from '../notifications/notifications.service';
import { DevcollabGateway } from '../gateway/devcollab.gateway';

@Injectable()
export class GithubService {
  private readonly logger = new Logger(GithubService.name);

  constructor(
    @InjectRepository(PlanEntity)
    private readonly plansRepo: Repository<PlanEntity>,
    private readonly notificationsService: NotificationsService,
    private readonly gateway: DevcollabGateway,
  ) {}

  async createPrToMain(user: UserEntity): Promise<{ prUrl: string; plans: string[] }> {
    if (![UserRole.PM, UserRole.TECHLEAD].includes(user.role)) {
      throw new ForbiddenException('Only PM or Tech Lead can create PRs to main');
    }

    // Get all QA_APPROVED plans
    const approvedPlans = await this.plansRepo.find({
      where: { status: PlanStatus.QA_APPROVED },
    });

    if (approvedPlans.length === 0) {
      throw new BadRequestException('No QA-approved plans available for release');
    }

    // Check for open blocking bugs on any approved plan
    for (const plan of approvedPlans) {
      const openBugs = await this.plansRepo.find({
        where: {
          parentPlanId: plan.id,
          type: PlanType.BUG,
          status: PlanStatus.OPEN,
        },
      });
      if (openBugs.length > 0) {
        throw new BadRequestException(
          `Plan ${plan.id} has ${openBugs.length} open bug(s): ${openBugs.map((b) => b.id).join(', ')}. Close all bugs before creating PR.`,
        );
      }
    }

    const planIds = approvedPlans.map((p) => p.id);
    const prBody = this.generatePrBody(approvedPlans);

    // Create GitHub PR
    const prUrl = await this.createGithubPr(prBody, user.username);

    await this.notificationsService.notifyPrCreated(planIds, prUrl);

    return { prUrl, plans: planIds };
  }

  private generatePrBody(plans: PlanEntity[]): string {
    const sections = plans.map((p) => {
      const criteria = JSON.parse(p.acceptanceCriteria) as { text: string; checked: boolean }[];
      return `### ${p.id}: ${p.title}
**Type:** ${p.type} | **Priority:** ${p.priority}
**Goal:** ${p.goal || 'N/A'}

**Acceptance Criteria:**
${criteria.map((c) => `- [${c.checked ? 'x' : ' '}] ${c.text}`).join('\n')}

**QA Notes:** ${p.qaNotes || 'N/A'}
`;
    });

    return `## Release PR — ${new Date().toISOString().split('T')[0]}

This PR merges the following QA-approved plans to production:

${sections.join('\n---\n')}

---
*Generated by DevCollab*`;
  }

  private async createGithubPr(body: string, username: string): Promise<string> {
    const token = process.env.GITHUB_TOKEN;
    const owner = process.env.GITHUB_OWNER;
    const repo = process.env.GITHUB_REPO;

    if (!token || !owner || !repo) {
      throw new BadRequestException('GitHub is not configured (GITHUB_TOKEN, GITHUB_OWNER, GITHUB_REPO missing)');
    }

    const response = await axios.post(
      `https://api.github.com/repos/${owner}/${repo}/pulls`,
      {
        title: `Release: ${new Date().toISOString().split('T')[0]} — QA Approved`,
        body,
        head: 'preview',
        base: 'main',
      },
      {
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: 'application/vnd.github+json',
        },
      },
    );

    return response.data.html_url;
  }

  async handleWebhook(payload: any): Promise<void> {
    // Detect PR merged to main
    if (
      payload.action === 'closed' &&
      payload.pull_request?.merged === true &&
      payload.pull_request?.base?.ref === 'main'
    ) {
      this.logger.log(`PR merged to main: #${payload.pull_request.number}`);

      // Mark all QA_APPROVED plans as DONE
      const approvedPlans = await this.plansRepo.find({
        where: { status: PlanStatus.QA_APPROVED },
      });

      const planIds = approvedPlans.map((p) => p.id);

      await this.plansRepo.update(
        { status: PlanStatus.QA_APPROVED },
        { status: PlanStatus.DONE, doneAt: new Date() },
      );

      this.gateway.emitPlanUpdated({ action: 'batch_done', planIds });
      await this.notificationsService.notifyMergedToProduction(planIds);

      this.logger.log(`Marked ${planIds.length} plans as DONE after production merge`);
    }
  }
}
